### ISSUE TITLE
App cannot be found on the Play Store

### ISSUE THREAD

**Issue by andresitodeguzman** [termux/termux-boot#1]
The link doesn't seem to direct me to the app

**Comment by jtp628** [comment]
ya its anoing

**Comment by fornwall** [comment]
The app is not yet released, but will be soon!

**Comment by andresitodeguzman** [comment]
Cool hahaha

**Comment by kutsan** [comment]
@fornwall Sorry Fredrikf for disturbing but how soon? Could you please give us additional info about alpha, beta, final release dates?
