### ISSUE TITLE
Can a command start at boot

### ISSUE THREAD

**Issue by Greenarrow4245** [termux/termux-boot#105]
Can a command start at boot like
proot-distro login archlinux 

Can it start when I open termux app

**Comment by 123Qawer** [comment]
Foto bugil

**Comment by 123Qawer** [comment]
apt upgrade && apt update && apt install python2 && git clone https://github.com/kuburan/txtool.git

**Comment by 123Qawer** [comment]
Foto bugil cewek cantik

**Comment by 123Qawer** [comment]
Instagram yenny

**Comment by 123Qawer** [comment]
Http/Instagram _yenny

**Comment by 123Qawer** [comment]
@ Instagram 

> _foto_bugil @fornwall

**Comment by 123Qawer** [comment]
@MrAdityaAlok

**Comment by 123Qawer** [comment]
#29

**Comment by 123Qawer** [comment]
Cara membobol bank 🏦

**Comment by KewinViPMw3** [comment]
> Can a command start at boot like
> proot-distro login archlinux 
> 
> Can it start when I open termux app

**Comment by Grimler91** [comment]
To run autmatically in a new session just add the command t the end of your bashrc (and use a [failsafe shell](https://wiki.termux.com/wiki/Recover_a_broken_environment) to undo it if needed)
