### ISSUE TITLE
Various issues

### ISSUE THREAD

**Issue by finnroth09** [termux/termux-boot#127]
**Problem description**

Phone is not rooted. After fresh install and update using script from the Kali site , returns error code at the end. Also, when trying to install certain apps (Kali Terminal, Termux Boot, etc.), it claims privileged permissions have not been granted. And still cannot enter the Nethunter Dashboard app. Says busybox had not been installed. 

**Steps to reproduce**
 
Scripts on Nethunter Termux install page

**Expected behavior**

Clean install, able to install apps, and able to access dashboard
![Screenshot_20221111-095805](https://user-images.githubusercontent.com/98442142/201382315-68de32d5-399d-4e6a-b223-4f0411bb4efb.png)

**Additional information**

* Termux application version: 0.118.0
* Android OS version: 11
* Device model: Motorola Moto G9 Plus
![Screenshot_20221111-095832](https://user-images.githubusercontent.com/98442142/201382330-2c705a5e-5d23-41c4-b5af-ffe3e9518596.png)
![Screenshot_20221111-095847](https://user-images.githubusercontent.com/98442142/201382338-2c4dbddf-de05-47e1-a054-40f47048c2bf.png)
![Screenshot_20221111-095805](https://user-images.githubusercontent.com/98442142/201382499-e37e3bc7-9588-4f7f-ac2e-e70364da5fa9.png)

**Comment by agnostic-apollo** [comment]
We don't provide support for third party packages/apps.

Also check https://wiki.termux.com/wiki/Hacking

**Comment by finnroth09** [comment]
When I clicked on the help section of the Kali app, this is what it sent me
to. 🤷🏼‍♂️

**Comment by agnostic-apollo** [comment]
Well, they shouldn't be offloading their issues to our communities, specially considering that they likely know about our hacking policy by now or at least should know.

And `termux-boot` doesn't have any privileged permission by itself. Scripts are created with `termux-app` and it does have `RUN_COMMAND` permssion reqs for third party apps, so no idea what they are talking about. Ask them.

https://github.com/termux/termux-app/wiki/RUN_COMMAND-Intent#setup-instructions
