### ISSUE TITLE
Universal Installed then opened and crashed. Arm64 would not install

### ISSUE THREAD

**Issue by LegnaNesir** [termux/termux-boot#130]
**Problem description**

**Steps to reproduce**
## Report Info

**User Action**: `crash report`  
**Sender**: `TermuxInstaller`  
**Report Timestamp**: `2022-11-18 17:42:50.449 UTC`  
##

## Bootstrap Error

(150) FileUtils Error: The termux files directory not found at path "/data/data/com.termux/files".
TERMUX_FILES_DIR: `/data/data/com.termux/files`

## Termux Files Info

**TERMUX_REQUIRED_FILES_DIR_PATH ($PREFIX)**: `/data/data/com.termux/files`  
**ANDROID_ASSIGNED_FILES_DIR_PATH**: `/mnt/expand/593f5bef-93da-4ab5-8aef-9387300cdf5c/user/0/com.termux/files`  

```
$ echo 'ls info:'
/system/bin/ls -lhdZ '/data/data' '/data/user/0' '/data/data/com.termux' '/data/user/0/com.termux' '/data/data/com.termux/files' '/mnt/expand/593f5bef-93da-4ab5-8aef-9387300cdf5c/user/0/com.termux/files' '/data/user/0/com.termux/files' '/data/user/com.termux/files' '/data/data/com.termux/files/usr-staging' '/data/data/com.termux/files/usr' '/data/data/com.termux/files/home' '/data/data/com.termux/files/usr/bin/login' 2>&1
echo; echo 'mount info:'
/system/bin/grep -E '( /data )|( /data/data )|( /data/user/[0-9]+ )' /proc/self/mountinfo 2>&1 | /system/bin/grep -v '/data_mirror' 2>&1

ls info:
ls: /data/data/com.termux: No such file or directory
ls: /data/user/0/com.termux: No such file or directory
ls: /data/data/com.termux/files: No such file or directory
ls: /data/user/0/com.termux/files: No such file or directory
ls: /data/user/com.termux/files: No such file or directory
ls: /data/data/com.termux/files/usr-staging: No such file or directory
ls: /data/data/com.termux/files/usr: No such file or directory
ls: /data/data/com.termux/files/home: No such file or directory
ls: /data/data/com.termux/files/usr/bin/login: No such file or directory
drwxrwx--x 272 system  system  u:object_r:system_data_file:s0                    52K 2022-11-18 10:15 /data/data
drwxrwx--x 272 system  system  u:object_r:system_data_file:s0                    52K 2022-11-18 10:15 /data/user/0
drwxrwx--x   2 u0_a238 u0_a238 u:object_r:app_data_file:s0:c238,c256,c512,c768  3.4K 2022-11-18 12:42 /mnt/expand/593f5bef-93da-4ab5-8aef-9387300cdf5c/user/0/com.termux/files

mount info:
1464 1290 253:8 / /data rw,nosuid,nodev,noatime master:30 - f2fs /dev/block/dm-8 rw,lazytime,seclabel,background_gc=on,discard,no_heap,user_xattr,inline_xattr,acl,inline_data,inline_dentry,flush_merge,extent_cache,mode=adaptive,active_logs=6,reserve_root=13149,resuid=0,resgid=1065,inlinecrypt,alloc_mode=default,fsync_mode=nobarrier
1465 1464 253:8 /data /data/user/0 rw,nosuid,nodev,noatime master:30 - f2fs /dev/block/dm-8 rw,lazytime,seclabel,background_gc=on,discard,no_heap,user_xattr,inline_xattr,acl,inline_data,inline_dentry,flush_merge,extent_cache,mode=adaptive,active_logs=6,reserve_root=13149,resuid=0,resgid=1065,inlinecrypt,alloc_mode=default,fsync_mode=nobarrier

```
##

## Logcat Dump

```
$ /system/bin/logcat -d -t 3000 2>&1

```
##

## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.118.0`  
**VERSION_CODE**: `118`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `true`  
**IS_INSTALLED_ON_EXTERNAL_STORAGE**: `true`  
**FILES_DIR**: `/mnt/expand/593f5bef-93da-4ab5-8aef-9387300cdf5c/user/0/com.termux/files`  
**TERMUX_FILES_DIR**: `/data/data/com.termux/files`  
**IS_TERMUX_FILES_DIR_ACCESSIBLE**: `false - (150) FileUtils Error: The termux files directory not found at path "/data/data/com.termux/files".`  
**APK_RELEASE**: `Github`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `B6DA01480EEFD5FBF2CD3771B8D1021EC791304BDD6C4BF41D3FAABAD48EE5E1`  
##

### Software

**OS_VERSION**: `4.19.157-perf`  
**SDK_INT**: `30`  
**RELEASE**: `11`  
**ID**: `MH-T6000V1.0.0B008`  
**DISPLAY**: `MH-T6000V1.0.0B008`  
**INCREMENTAL**: `220825`  
**SECURITY_PATCH**: `2022-09-05`  
**IS_DEBUGGABLE**: `0`  
**IS_TREBLE_ENABLED**: `true`  
**TYPE**: `user`  
**TAGS**: `release-keys`  

### Hardware

**MANUFACTURER**: `KonnectONE`  
**BRAND**: `moxee`  
**MODEL**: `MH-T6000`  
**PRODUCT**: `MH-T6000`  
**BOARD**: `msm8937`  
**HARDWARE**: `qcom`  
**DEVICE**: `MH-T6000`  
**SUPPORTED_ABIS**: `armeabi-v7a, armeabi`  
##

**Expected behavior**
the program to function normally

**Additional information**

* Termux application version:
* Android OS version:
* Device model:

**Comment by agnostic-apollo** [comment]
Don't install termux apps on external sd card.

**Comment by TomJo2000** [comment]
To elaborate on this.
Termux does not have the necessary permissions to install packages to locations outside of its own app directory due to Android limitations.
As such all packages must be installed to internal storage, and access to SD cards or attached USB devices is limited.

**Comment by omb714-1980** [comment]
Is this device rootable? I cant find much info on it at all I was shocked to see this thread with the same device info as mine

**Comment by LegnaNesir** [comment]
I do not yet know. It's the only active working phone I have at the moment
so Im hesitant to risk it. But I was able to get Termux Installed properly
and didn't have to remove the removabl dr
