### ISSUE TITLE
use it to enhance termux-service

### ISSUE THREAD

**Issue by cxyzzz** [termux/termux-boot#143]
**Feature description**

The Termux:Boot plugin can run scripts after phone boot complete. Is there a way to use Termux:Boot initialize termux-service? Then the termux-service can create a services run after phone boot complete.

**Comment by Grimler91** [comment]
If you are using bash you can use 

```
#!/data/data/com.termux/files/usr/bin/sh
termux-wake-lock
. $PREFIX/etc/profile
```

See wiki: https://wiki.termux.com/wiki/Termux:Boot

**Comment by cxyzzz** [comment]
> If you are using bash you can use
> 
> ```
> #!/data/data/com.termux/files/usr/bin/sh
> termux-wake-lock
> . $PREFIX/etc/profile
> ```
> 
> See wiki: https://wiki.termux.com/wiki/Termux:Boot

Thanks
