### ISSUE TITLE
GH build expired

### ISSUE THREAD

**Issue by ae14** [termux/termux-boot#149]
**Make the last GH build available**
I would like to download a build of termux-boot from GH as opposed to F-droid but the last workflow artifact has expired for download https://github.com/termux/termux-boot/actions/runs/3406859282 The only way to install termux-boot is to uninstall and start over via the F-droid route.
Already started over to install the most recent GH build of termux-app in order to make use of the termux-saf-* tools (unsuccessfully) and would like to continue to use the latest builds of the termux packages as opposed to having to switch back to F-droid to get the boot tool working again.
Many thanks for all of your efforts, a truly excellent project.

**Comment by Grimler91** [comment]
I've updated the README, so a new build will shortly be available at https://github.com/termux/termux-boot/actions/runs/4391982642, thanks for reporting!
