### ISSUE TITLE
Termux:boot not working on android 13

### ISSUE THREAD

**Issue by heyaitsarrow** [termux/termux-boot#152]
Hey, I have a Samsung Galaxy S20 FE 5G and it doesn't install. It says: package conflict with an existing package

**Comment by Lazymaz** [comment]
I downloaded termux from github and termux:boot from f-droid

**Comment by TomJo2000** [comment]
> I downloaded termux from github and termux:boot from f-droid

You can't mix and match like that, they have different signing keys.
If you're using a GitHub build of Termux you'll need a GitHub build of Termux:Boot
