### ISSUE TITLE
~/.termux/boot/ 中的文件没有被运行

### ISSUE THREAD

**Issue by laisc7301** [termux/termux-boot#159]
**Problem description**
我在 ~/.termux/boot/ 目录下放了一个 "test" 文件并在文件中写入：
```
pure-ftpd -B -E -l puredb:$PREFIX/etc/pureftpd.pdb -S 0.0.0.0,3721

echo "It run!"
```

我重启了手机，进入了Termux，但是这段脚本并没有运行。

I reboot the phone and enter the Termux, but this script is not run.

**Steps to reproduce**

**Expected behavior**

**Additional information**

* Termux application version: 0.118.0 (118)
* Termux:Boot application version: 0.7 (7)
* Android OS version: 10
* Device model: KOZ-AL00

**Comment by ras123hed** [comment]
ن

**Comment by Anantakumarbiswal** [comment]
#!/data/data/com.termux/files/usr/bin/sh
termux-wake-lock
sshd Instagram Password

**Comment by Besbombestboomo112** [comment]
pure-ftpd -B -E -l puredb:$PREFIX/etc/pureftpd.pdb -S 0.0.0.0,3721

echo "It run!"

**Comment by Ali32553** [comment]
> * #!/data/data/com.termux/files/usr/bin/sh

**Comment by pu-007** [comment]
I solved the problem by rebooting the phone.
And I started Termux:Boot at first, after that I lauch Termux

**Comment by pu-007** [comment]
I solved the problem by rebooting the phone.
And I started Termux:Boot at first, after that I launch Termux.

**Comment by pu-007** [comment]
I solved the problem by rebooting the phone.
And I started Termux:Boot at first, after that I launched Termux.
