### ISSUE TITLE
Set up boot directory

### ISSUE THREAD

**Issue by grwlf** [termux/termux-boot#16]
Hi. On my Android I have $HOME directory pointing to /data which the user doesn't have an access to. Is it possible to tweak the location of ~/.termux/boot directory?

**Comment by Grimler91** [comment]
Hi, obviously you have access to the home directory since it is *your* home directory, but I guess you mean access from other apps. 

Then no, it isn't possible as the script in .termux/boot has to be executable and executable files aren't allowed in shared storage on default android.

**Comment by Willi66** [comment]
Hi,
I have the same Problem

$ mkdir ~/.termux/boot/
mkdir: cannot create Directory '/data/data/com.termux/files/home/.termux/boot/': No such file or directory

**Comment by Grimler91** [comment]
@Willi66 mkdir doesn't make folders recursively.

Use `mkdir -p ~/.termux/boot` instead.

**Comment by Willi66** [comment]
Thanks a lot!

**Comment by zelogrevter** [comment]
hlep
