### ISSUE TITLE
Node-Red Not Found

### ISSUE THREAD

**Issue by claudiobadii** [termux/termux-boot#17]
Hi,

I installed both termux-app and termux-boot. In termux-app I followed the node-red official guide and it was possible from terminal to find and to run  the program. Inserting the command inside a file under the directory ~/.termux/boot and debugging the call, it was possible to see that the file is called but on the node-red line the log write:

node-red: not found
![screenshot_20180702-122515](https://user-images.githubusercontent.com/7081445/42159144-fea04142-7df2-11e8-82b0-f7be55cc2d57.png)

**Comment by Grimler91** [comment]
Try running `termux-fix-shebang $(which node-red)`, termux-boot requires valid shebangs.

**Comment by claudiobadii** [comment]
Thank you! It work at the first try. :-)
