### ISSUE TITLE
virus in termux:boot?

### ISSUE THREAD

**Issue by LinuxOpa** [termux/termux-boot#170]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

* Termux application version: latest
* Android OS version: 11
* Device model: realme 
![termux-boot-playstore](https://github.com/termux/termux-boot/assets/41851582/48d1883a-81a0-472a-981e-b08f698fb586)
![termux-boot-virustotal](https://github.com/termux/termux-boot/assets/41851582/a8d6cf12-eb98-4781-922e-dbd3c1a726e0)

**Comment by agnostic-apollo** [comment]
Would be a false positive, only one vendor marked it. And by it's name, connectivity check is not a virus.

**Comment by LinuxOpa** [comment]
ok, thanks
