### ISSUE TITLE
won't install on Android 14 on Pixel 7a

### ISSUE THREAD

**Issue by Steve-Newcomb** [termux/termux-boot#198]
**Problem description**

I try to install termux:boot from F-Droid but I'm not permitted to do it because it was built for an earlier version (of Android, I assume).

**Steps to reproduce**

(1) Go to f-droid.
(2) Install termux:boot.

**Expected behavior**

I would expect termux:boot to install.
**Additional information**

* Termux application version: current on F-Droid
* Android OS version: 14
* Device model: Pixel 7a

**Comment by twaik** [comment]
https://github.com/termux/termux-app/blob/master/README.md#installation
