### ISSUE TITLE
Executing Multiple Scripts at boot

### ISSUE THREAD

**Issue by TrueBananaShark** [termux/termux-boot#22]
Hi there.

Am completely new to this but will give it my best shot:

Am running termux on my nexus 7 and want it to run both node-red and mosquitto at boot

For this i created 2 files in .termux/boot **start-nodered** and **start-mosquitto**

**start-nodered** has the following in it:

_termux-wake-lock
termux-fix-shebang $(which node-red)
node-red_

and **start-mosquitto** has:

_termux-wake-lock
mosquitto_

The problem I have is that only one of the scripts seems to run when I need them both to start.

If I delete **start-nodered** then mosquitto starts up perfectly or if I delete **start-mosquitto** then node-red works fine.

When they are both in there node red starts and not mosquitto.

My guess is that it gets stuck running one and doesn't move on to the other?

If anyone could help me with this it would be much appreciated.

Thanks

**Comment by Grimler91** [comment]
Try moving them to background, use `node-red &` and `mosquitto &`. 

It's probably good to set a shebang as well, put `#!/data/data/com.termux/files/usr/bin/sh` as the first line of both scripts.

**Comment by TrueBananaShark** [comment]
Hi

Changed **start-nodered** to :

_#!/data/data/com.termux/files/usr/bin/sh
termux-wake-lock
termux-fix-shebang $(which node-red)
node-red &_

and **start-mosquitto** to:

_#!/data/data/com.termux/files/usr/bin/sh
termux-wake-lock
mosquitto &_

as you suggested, unfortunately I seemed to be having the same problem.

An idea jumped into my head and I deleted both scripts and made a new one named **startup**

in **startup** I put this code:

_#!/data/data/com.termux/files/usr/bin/sh
termux-wake-lock
termux-fix-shebang $(which node-red)
node-red & mosquitto_

**And it worked !!!**

I don't know why I thought it would work but I'm guessing it ran both commands simultaneously?

Anyway it worked for me, thank you so much Grimler for your help !!!

It's not a perfect solution however so I'm willing to continue testing if anyone wants to help find another solution in case someone else has a similar issue.


From more testing it seems that **node-red** is always the one that starts when they are both in there, I'm guessing the scripts activate alphabetically?

When I run the node-red command manually i cannot input any other commands unless I **_Ctrl-C_** to get out of it, could the problem be related to this ?

**Comment by TrueBananaShark** [comment]
Just added _sshd_ to the script as well so the end of the script looks like this:

_node-red & mosquitto & sshd &_

All of them are working perfectly.

Thank you Grimler !!!

**Comment by manueldiasmanuel** [comment]
> termux-wake-lock
> termux-fix-shebang $(which node-red)
> node-red

Hello ,

Did you write this script on a TXT file or  ?   

Thanks,

MD

**Comment by manueldiasmanuel** [comment]
I am missing something .... how do i create a script file for boot with Termux . I mena what type of file i need to use ?   A simple .txt is enought ? 

MD

**Comment by TrueBananaShark** [comment]
> I am missing something .... how do i create a script file for boot with Termux . I mena what type of file i need to use ? A simple .txt is enought ?
> 
> MD

Hi there.

I'm not sure if it is the best way, but I just used the nano command from within termux to create the files.

e.x nano node-red edits the file node red in the current directory and if it's not there it creates it.

I believe they come out as a normal text file that way but I'm not 100% sure.

**Comment by manueldiasmanuel** [comment]
Hi,

Thank you !

Your instructions were very useful and node-red is  now running when i restart my android system. 
 
Regarding  the file type ;   I have  edited a  text  file  created in Windows using the nano node-red editor and a  message  appeared " converted from MS-DOS " .   I also have  copied a file created  with nano node-red  and move it to Windows and in the properties the file type shown is ;  " file" .

Regards,

MD

**Comment by manueldiasmanuel** [comment]
How  to change the node-red setting.js  files ?   Where is  the setting.js file  path that node-red  is " reading " when it starts up by script ?  
I  remote access Termux by FTP server with this command    $ tcpsvd -vE 0.0.0.0 1024 ftpd -w /.
I´ve found  one node-red setting.js , i´ve  change  the settings i wanted for authentication but had nothing happen when i start node-red session ?  Any ideas ?

**Comment by TrueBananaShark** [comment]
Hi there.

The settings.js file (if you didn't specify otherwise) should be in the default folder in termux.

Internally (from within termux) it's located in:  " /files/home/.node-red "
Externally (ftp server looking in) it's in : " data/data/com.termux/files/home/.node-red "

I believe .node-red is a hidden file so you may need to change a setting to be able to see it.

Unfortunately to access it externally I believe you may have to have root access on your device. A way around this would be to use the command "termux-setup-storage" and then move them around with an ssh tool.

If you want, you can read more on that here: https://android.stackexchange.com/questions/166595/termux-how-do-i-create-a-directory-of-files-accessible-outside-of-termux/166637#166637

Easiest way to check if you have the right settings file is to use the nano command to edit it, and then change the ui port from 1880 (its Default) to 1885 or something else. Then see if it changes when you reboot the device, if it does you have the corrects settings file.

I'm not an expert on the subject but I hope I have helped at least a little.

Let me know how you get on.

**Comment by manueldiasmanuel** [comment]
Hi,

I used nano node-red editor to edit  the file  settings.js and now node-red  is  working  with as i needed with  new settings ! 

To understand better this process i will try to install  Termux and node-red in different device to learn a bit more.

There are a few commands  used inside of Termux terminal that were very useful  for me ;   cp +file + target directory path   ( copy  file from  current directory to another one ).
mv ( the same as copy but only moving)

I will  repeat the entire installation in different device for better understanding the process. I´ve played to much that i am a bit lost on the steps i took.

Thank you very much for your help.



Regards,

MD

**Comment by TrueBananaShark** [comment]
No problem
