### ISSUE TITLE
Hacking 

### ISSUE THREAD

**Issue by Aki87229** [termux/termux-boot#225]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

* Termux application version:
* Android OS version:
* Device model:

**Comment by Aki87229** [comment]
I want hack jhana RM s gardose because she's cheat me on her ex boyfriend

**Comment by Aki87229** [comment]
I want open her account because i see me oh her chat

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-community/blob/site/site/pages/en/rules/hacking.md

**Comment by twaik** [comment]
https://wiki.termux.com/wiki/Hacking
