### ISSUE TITLE
Write a script

### ISSUE THREAD

**Issue by paulsavo1** [termux/termux-boot#24]
Hi im new to this and a bit lost, im trying to get a programm to run on start

i have created the boot folder and know how to copy .sh file into it and have used  
logcat -s termux:* and can confirm that the .sh file is booting at startup but the program is not actually starting so im obviously not getting the script right

im trying to start a program called sstvProxy.py

it is located here /sdcard/sstvProxy/sstvProxy.py

what i have put in my .sh file is this

#!/bin/bash
python /sdcard/sstvProxy/sstvProxy.py -hl

but it is not working

can someone please help as im really struggling

**Comment by paulsavo1** [comment]
cheers for response so is that what proper script look like

/data/data/com.termux/files/usr/bin/bash
chmod u+x python /sdcard/sstvProxy/sstvProxy.py -hl

**Comment by Grimler91** [comment]
Well, almost.

Try 
```
#!/data/data/com.termux/files/usr/bin/bash
python /sdcard/sstvProxy/sstvProxy.py -hl
```

And you might need to run `chmod u+x ˜/.termux/boot/your_script_name` to make it executable.

**Comment by paulsavo1** [comment]
does the chmod bit just get added after the 1st 2 lines?

**Comment by Grimler91** [comment]
Try without the chmod part first. 

You can learn more about what it does here: https://askubuntu.com/questions/443789/what-does-chmod-x-filename-do-and-how-do-i-use-it

**Comment by Grimler91** [comment]
If the logcat says that it is running then I would assume that it is running but that something is wrong in the sstvProxy.py script

**Comment by paulsavo1** [comment]
cheers can you point me to what it might be, the command to run the actual py file is just simply

python /sdcard/sstvProxy/sstvProxy.py - hl

so what should the script look like to run this in termux/boot

**Comment by paulsavo1** [comment]
ok mate it is something to do with termux or termux boot although it is saying in logcat that it is running i dont think it is, as when i simple type
~/.termux/boot/sstvProxy.sh 
the program starts, so the script must be correct, is there something preventing it from opening

**Comment by Grimler91** [comment]
>  when i simple type ~/.termux/boot/sstvProxy.sh the program starts

What does "the program starts" mean? How are you verifying this? 
What does the script actually do?

I would try to replace the script with something else that is easy to verify, like 
```
#!/data/data/com.termux/files/usr/bin/bash
echo `dateˋ >> ˜/boot.log
```
If that works then you know it is executed, if it doesn't work then the problem is with termux-boot

**Comment by paulsavo1** [comment]
hi the script is supposed to input a python command at startup that i would normally have to input manually.

It is a program that runs a proxy iptv m3u8 url so i can access on other devices

I know the script seems to work as when i just input manually the folder it is located in, then the proxy program starts and data is sent to my devices

i am in work so i will try the other script when i get home

**Comment by paulsavo1** [comment]
any idea mate?
