### ISSUE TITLE
Unable install to bootstrap 

### ISSUE THREAD

**Issue by DHANAVATHgANESH** [termux/termux-boot#242]
![Screenshot_20241126_212110_Termux](https://github.com/user-attachments/assets/5f2612eb-2406-4019-bd65-2a27ef14f646)

**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

* Termux application version:
* Android OS version:
* Device model:

**Comment by twaik** [comment]
Duplicate of https://github.com/termux/termux-boot/issues/241
