### ISSUE TITLE
ffmpeg issues

### ISSUE THREAD

**Issue by paulsavo1** [termux/termux-boot#27]
Hi folks can someone please help, i have a script that runs a proxy so i get live tv for plex, in order for the channels to play plex needs ffmpeg which i have installed, once i type the python script everything works great

however what i wanted to do was have it auto start, i have used both termux tasker and boot and and using both formats the script is loading the proxy with no issues 

The problem is that ffmpeg does not appear to loadusing either of these methods, it should start automatically when terux starts but it is not

any ideas?

**Comment by fornwall** [comment]
Hello! I think you will have better answers asking for help at https://www.reddit.com/r/termux/ or  https://gitter.im/termux/termux!
