### ISSUE TITLE
sshd not started at boot

### ISSUE THREAD

**Issue by huangyg11** [termux/termux-boot#3]
I create file in ~/.termux/boot/start-sshd with content:

```
termux-wake-lock
sshd
```

but when reboot the device, sshd is not running.

How can I debug this problem?

**Comment by fornwall** [comment]
You need to install Termux:Boot and launch the Termux:Boot app once to have this working!

**Comment by dedynobre** [comment]
create file in ~/.termux/boot/start-nr with content:

termux-wake-lock
node-red

But is not working.

I have the termux:boot installed.
