### ISSUE TITLE
Asking for Help from a Customer

### ISSUE THREAD

**Issue by MCTyler** [termux/termux-boot#31]
Will this actually run my Binary file in my home directory at Boot? Haven't tested it yet cause people are using the Shield for Live TV Viewing....Thanks! Also, How can I get it to run in a detached screen?
-------------------------------------------------------------------
 termux-wake-lock
 termux-chroot
 cd ~/
 ./xteverun -port"8080"
------------------------------------------------------------------

**Comment by MCTyler** [comment]
$ logcat -s termux:*
--------- beginning of main
01-05 17:37:23.088  6920  6920 I termux  : Executed files at boot: start-sshd, xteve-chroot, xteve.sh
But I can't connect VIA ssh and nothing else is running except chroot

**Comment by MCTyler** [comment]
Figured it out...your instructions are not great...JS. Thx for the great App though!

**Comment by Grimler91** [comment]
@MCTyler Feel free to contribute and improve the instructions, this is an open-source project after all

**Comment by MCTyler** [comment]
Just putting it all in 1 file works...separate scripts don't...
   ```termux-wake-lock
    sshd
    cd ~/
    screen -wipe
    sleep 10
    screen -d -m termux-chroot ./xteverun -port="8080"```

**Comment by MCTyler** [comment]
Termux:Boot
This addon will run scripts immediately after device was booted.

Installation
F-Droid
Google Play
Important: Do not mix installations of Termux and Addons between Google Play and F-Droid. They are presented at these portals for your convenience. There are compatibility issues when mixing installations from these Internet portals. This is because each download website uses a specific key for keysigning Termux and Addons.

Usage
Install the Termux
Boot app.
Start the Termux
Boot app once by clicking on its launcher icon. This allows the app to be run at boot.
Create the ~/.termux/boot/ directory
-------------------------------------------------------------------------------------------------------------------------------------------
Put scripts you want to execute inside the ~/.termux/boot/ directory. If there are multiple files, they will be executed in a sorted order.
-------------------------------------------------------------------------------------------------------------------------------------------
Note that you may want to run termux-wake-lock as first thing if you want to ensure that the device is prevented from sleeping.

Example: to start an sshd server and prevent the device from sleeping at boot, create the following file at ~/.termux/boot/start-sshd:

termux-wake-lock
sshd
