### ISSUE TITLE
BOOT_COMPLETED: process is bad

### ISSUE THREAD

**Issue by roman-rybalko** [termux/termux-boot#35]
**Problem description**
`com.termux.boot` is not starting at system boot. Startup scripts are not executed.

**Steps to reproduce**
*What does your termux-boot script contain?*
```
$ ls -l ~/.termux/boot/
total 16
-rwx------    1 u0_a54   u0_a54          17 Jun 27 00:41 00-wake-lock.sh
-rwx--x--x    1 u0_a54   u0_a54           5 Jun 27 00:41 10-sshd.sh
-rwx--x--x    1 u0_a54   u0_a54          72 Jun 27 01:09 20-ftpd.sh
-rwx--x--x    1 u0_a54   u0_a54          66 Jun 27 01:22 30-httpd.sh
$ 
```
*Please post the full script here.*
```
$ cat ~/.termux/boot/*
termux-wake-lock
sshd
/system/bin/logwrapper tcpsvd -vE 0.0.0.0 10021 ftpd -w $HOME/storage &
/system/bin/logwrapper lighttpd -D -f $PREFIX/etc/lighttpd.conf &
$ 
```

**Expected behavior**
Scripts in the ~/.termux/boot/ are started at system boot.

**Additional information**
*Post output of command `termux-info`.*
```
$ termux-info 
Updatable packages:
openssl/stable 1.1.1c-1 aarch64 [upgradable from: 1.1.1c]
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 3.10.104 #160 SMP PREEMPT Fri Sep 22 12:59:52 CST 2017 aarch64 Android
Termux-packages arch:
aarch64
Android version:
7.1.2
Device manufacturer:
rockchip
Device model:
RockBox-Basic
$ 
```
*If you are rooted or have access to adb then capture a logcat with `logcat -d "*:W"`, from a adb or root shell.*
[logcat.txt](https://pastebin.com/XzreaDnA)

**Comment by roman-rybalko** [comment]
I'm going to start `com.termux.boot` from `/system/etc/init.d`.
What activity do I need to execute?
Could you please provide me the `am ...` command please.
Thanks!

**Comment by roman-rybalko** [comment]
Can I execute a script directly in the com.termux instance?
According to [BootJobService.java:21](https://github.com/termux/termux-boot/blob/master/app/src/main/java/com/termux/boot/BootJobService.java#L21) there is a service that accepts the following intent: `am startservice -n com.termux/com.termux.app.TermuxService -a com.termux.service_execute -d com.termux.file:///data/data/com.termux/files/home/autorun.sh --ez com.termux.execute.background true`. Will that work?
FYI: [am command manual](https://gist.github.com/tsohr/5711945).

**Comment by roman-rybalko** [comment]
Though that `am` command is working under `su` I can't manage to run it under `init`. Suggesting `selinux` prevents that. Also, there is time sync problem on my system, many things at boot do not work as expected before the time is synced.

Moved the app to /system. `BOOT_COMPLETED` is handled now.

**Comment by izzatillavaliev87** [comment]
[Kali linux](Submit new issue  © 2020 GitHub, Inc.TermsPrivacySecurityStatusHelpContact GitHubPricingAPITrainingBlogAbout) `
