### ISSUE TITLE
Android x86 RC2 support?

### ISSUE THREAD

**Issue by reardenlife** [termux/termux-boot#37]
Tried to install Termux Boot from FDroid on Android x86 8.1 RC2 (64 bit).  Got an "Unexpected error" during installation.  Should I provide debug logs or, perhaps just figure out how to setup autorun manually?

**Comment by Grimler91** [comment]
Did you install termux-app from play-store? Apps from fdroid and play store are signed with different keys and can therefore not be installed at the same time. Either install all apps from fdroid or all apps from play store.

**Comment by reardenlife** [comment]
@Grimler91
> "Did you install termux-app from play-store? "

Yes.  I did.

> "Apps from fdroid and play store are signed with different keys and can therefore not be installed at the same time."
I see.  :)
