### ISSUE TITLE
Playstore Link broken / unavailable

### ISSUE THREAD

**Issue by ksbckr** [termux/termux-boot#4]
Hey, 
just wanted to install the addon, but the Playstore Link seems to be broken. In fact, the app isn't available in the Playstore at all. Is there any plan to upload/reupload the app?

Thanks

**Comment by vimagick** [comment]
This is a very usefully app. Wish it release soon. 👍

**Comment by pranavg189** [comment]
Please give some status on the development of this app or please release it on F-Droid or Play Store. This is one of the most needed functionality in Termux. If needed, I will be happy to help with writing and maintaining the code for this app.

Regards.

**Comment by TilliWilli5** [comment]
+1 i need it

**Comment by fornwall** [comment]
The app is now published on Google Play and has been submitted to F-Droid for inclusion (https://gitlab.com/fdroid/fdroiddata/merge_requests/2438).
