### ISSUE TITLE
Termux:Boot doesn't work on andriod v9.0.0.

### ISSUE THREAD

**Issue by NightfallAlicorn** [termux/termux-boot#40]
**Problem description**
I've made a script under `~/.termux/boot/` and from the example tried:

```shell
#!/data/data/com.termux/files/usr/bin/sh
termux-wake-lock
a
```

I've even tried `bash` at the end of the shebang.

**Steps to reproduce**
`a` is an alias command in `~/.bashrc` with following contents:

```shell
alias a="cd ~/storage/shared/ariel-bot/ && forever index.js"
```

I've tried calling the script without the `a` alias and still doesn't work.

**Expected behavior**
The forever app should be running a nodejs script in the background. It works fine with the alias but doesn't work when device boots.

**Additional information**
```
termux-info
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 3.18.91-16437721 #1 SMP PREEMPT Wed Jul 24 15:53:54 KST 2019 armv8l Android
Termux-packages arch:
arm
Android version:
9
Device manufacturer:
samsung
Device model:
SM-J330FN
$
```

**Comment by Grimler91** [comment]
What's the shebang of the "forever" script?

**Comment by NightfallAlicorn** [comment]
It's an application from npm. After glancing at its github source https://github.com/foreversd/forever it looks like a parent process handler to run the target child script.

I've done some testing by adding this under termux-wake-lock `echo "hello world" > ~/storage/shared/ariel-bot/output.txt` Seems to write the file fine on boot.

Not sure what the problem is between the boot and running a continuous background script.

**Comment by Grimler91** [comment]
`head $(which forever)` will probably show that the shebang is `#!/usr/bin/env node` (which won't work in termux) based on that github repo. Either edit the script to use  `#!/data/data/com.termux/files/usr/bin/env node` or change your boot script so that it doesn't rely on forever's shebang (I.e. change `forever index.js` to `node forever index.js` in your script.

**Comment by NightfallAlicorn** [comment]
I got it to work with node on its own. I had no luck with changing the shebang to node or running `node forever index.js`

Guess I'll have to find an alternative to forever or somehow edit my script to run it.

Thanks for the help, guys.

**Comment by MCTyler** [comment]
Is this the same issue as it not installing on Nvidia Shield anymore?

**Comment by NightfallAlicorn** [comment]
I thought I post my working solution as a future reference and so that I can close this issue.

---

(Be sure to run `termux-setup-storage` to access internal storage and to open Termux:Boot Android application at least once.)

**~/.termux/boot/init**

```sh
#!data/data/com.termux/files/usr/bin/sh
termux-wake-lock
node ~/storage/shared/index.js
```

I've found when Android starts up. It'll automatically `chmod +x init` under `~/.termux/boot/init`

Also, using node as a shebang (#!data/data/com.termux/files/usr/bin/node, #!data/data/com.termux/files/usr/bin/env node, etc) doesn't seem to work.

Lastly, if anyone using node wants to restart their server if lose of Mobile Data or WiFi connection.

```js
const cp = require('child_process')

// Call this function with other needed error catch methods when a restart is required.
const restartServer = function restartServer () {
  console.log('Restarting server in 60 seconds...')
  setTimeout(() => {
    console.log('Restarting server...')
    cp.spawn(process.argv[0], process.argv.slice(1), {
      detached: true,
      stdio: ['ignore', 'inherit']
    }).unref()
    process.exit()
  }, 60000)
}

process.on('uncaughtException', (error, origin) => {
  console.error(error.message)
  restartServer()
})
```

The console logs can't be seen when started with Termux:Boot but are there for debugging by manually running the node script in Termux.

**Comment by xeffyr** [comment]
> #!data/data/com.termux/files/usr/bin/sh
> #!data/data/com.termux/files/usr/bin/node, #!data/data/com.termux/files/usr/bin/env node, etc

All these shebangs are incorrect. Should be in format `#!+/absolute/path/to/program`, example:
```
#!/data/data/com.termux/files/usr/bin/sh
```

Your shebangs cause:
![Screenshot_20191117-125723_Termux](https://user-images.githubusercontent.com/25881154/69006612-01bae480-093a-11ea-8df5-9fe398fff13a.jpg)
