### ISSUE TITLE
Side Load Termux Boot fails on Nvidia Sheild

### ISSUE THREAD

**Issue by MCTyler** [termux/termux-boot#42]
**Problem description**
Side Load of App ends with message "App not Installed"

**Steps to reproduce**
Upload Termux Boot from App Backup file (sideLoad) Install.

**Expected behavior**
Before Shield update it would install

**Additional information**
$ termux-info
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://termux.org/packages stable/main
System information:
Linux localhost 4.9.140-tegra-g68283f0ff762 #6 SMP PREEMPT Wed Sep 25 22:55:53 PDT 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
NVIDIA
Device model:
SHIELD Android TV

**Comment by MCTyler** [comment]
I noticed you guys submitted a refund.....Thanks but I'd rather have the App work on my Shield :(

**Comment by kimpenhaus** [comment]
I'd like to see this as well 👍 
It might be related to #18

**Comment by MCTyler** [comment]
Considering I was refunded, I don't think they are interested in supporting this....
