### ISSUE TITLE
Got an error when installing from F-Droid

### ISSUE THREAD

**Issue by brnyza** [termux/termux-boot#54]
Error Message:
Error installing Termux:Boot
Failed to install due to an unknown error

![image](https://user-images.githubusercontent.com/4684660/103152039-bab93880-4762-11eb-98dd-66ff569406b9.png)

* Termux application version:
* Android OS version: 8.1.0.0
* Device model: Motorola G5s

**Comment by Grimler91** [comment]
You need to install all termux apps (termux-app, termux-api, termux-boot, ..) from one source only. Apps on google play and fdroid are signed with different keys so are incompatible. See also https://wiki.termux.com/wiki/Installing_from_F-Droid
