### ISSUE TITLE
Trojans in Termux-Boot?

### ISSUE THREAD

**Issue by LinuxOpa** [termux/termux-boot#60]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

* Termux application version: Latest
* Android OS version: 8.0
* Device model: Cubot X18Plus
---
**a scan on VirusTotal:**
* CAT-QuickHeal Android.Boogr.A14b6
* Kaspersky HEUR:Trojan.AndroidOS.Boogr.gsh
* ZoneAlarm by Check Point HEUR:Trojan.AndroidOS.Boogr.gsh

on Termux-Boot = Termux:Boot_base.apk

and:

**Mail Problem:**
<contact@termux.com>: host mx.zoho.com[136.143.191.44] said: 552 5.1.1
<contact@termux.com> Mailbox delivery failure policy error (in reply to RCPT TO command)

**Comment by xeffyr** [comment]
> a scan on VirusTotal

False positive. Really here is situation that Termux:Boot uses some trojan patterns or a trojan borrowed some parts of Termux:Boot.

> Mail Problem:

Report Mail issues to @fornwall. I really have no idea whether it works at all...

**Comment by LinuxOpa** [comment]
That's what I thought, but caution is better than damage.
