### ISSUE TITLE
Cannot install on Android 10 Termux-boot APP

### ISSUE THREAD

**Issue by CH-WangMing** [termux/termux-boot#61]
Termux downloaded from f-droid: boot (v 0.7) cannot be installed on Android 10

**Comment by Grimler91** [comment]
You need to install all termux apps (termux-app, termux-api, termux-boot, ..) from one source only. Apps on google play and fdroid are signed with different keys so are incompatible. See also https://wiki.termux.com/wiki/Installing_from_F-Droid
