### ISSUE TITLE
Nothing happens with apachectl

### ISSUE THREAD

**Issue by jitumobile** [termux/termux-boot#83]
I installed Termux-boot app..and followed all steps.. I created a file named start-apache in boot directory with 2 line codes in it

termux-wake-lock
apachectl

but nothing happens..

**Comment by Grimler91** [comment]
Set a shebang as well, see example in README: https://github.com/termux/termux-boot#how-to-use

**Comment by Nadzieja83** [comment]
> I installed Termux-boot app..and followed all steps.. I created a file named start-apache in boot directory with 2 line codes in it
> 
> termux-wake-lock apachectl
> 
> but nothing happens..
