### ISSUE TITLE
Ji ksk

### ISSUE THREAD

**Issue by Sohaibbentourqi** [termux/termux-boot#84]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

* Termux application version:
* Android OS version:
* Device model:

**Comment by Sohaibbentourqi** [comment]
It's a great app more progress

**Comment by Sohaibbentourqi** [comment]
We wish you more success

**Comment by thunder-coding** [comment]
Consider being more professional on a professional platform!

**Comment by agnostic-apollo** [comment]
We wish you not waste our time.
