### ISSUE TITLE
termux:boot apk on github

### ISSUE THREAD

**Issue by 5p0ng3b0b** [termux/termux-boot#96]
The F-Droid version of Termux:Boot will not install with a version of Termux downloaded from github and the F-Droid is the only available source for the Termux:boot apk. Please compile a release of Termux:boot on github that works with github releases of Termux. It gets a bit frustrating having to start all over again!

**Comment by Grimler91** [comment]
Download and extract the artifact from the latest github actions build: https://github.com/termux/termux-boot/suites/7197605649/artifacts/287729256

**Comment by ch0rus** [comment]
All the artifacts from Actions are expired and can not be downloaded
